# Generated by Django 6.0.3 on 2026-05-26 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
    ]

    initial = True

    operations = [
        migrations.CreateModel(
            name='ExchangeRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_date', models.DateField(verbose_name='Fecha valor')),
                ('source', models.CharField(choices=[('bcv', 'BCV'), ('dolarapi', 'DolarAPI')], default='bcv', max_length=20, verbose_name='Fuente')),
                ('currency', models.CharField(choices=[('USD', 'Dolar'), ('EUR', 'Euro')], max_length=3, verbose_name='Moneda')),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20, verbose_name='Tasa')),
                ('fetched_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualizacion')),
                ('raw_label', models.CharField(blank=True, max_length=120, verbose_name='Etiqueta original')),
            ],
            options={
                'verbose_name': 'Historico de tasa',
                'verbose_name_plural': 'Historicos de tasas',
                'ordering': ('-rate_date', 'currency'),
                'unique_together': {('rate_date', 'source', 'currency')},
            },
        ),
    ]