# Generated by Django 6.0.5 on 2026-05-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='Color (Hex)')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
            },
        ),
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuations', to='organizations.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Valuación',
                'verbose_name_plural': 'Valuaciones',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de referencia')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('status', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('amount_bs', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto en Bolívares')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Monto en Dólares')),
                ('daily_rate', models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Tasa del día')),
                ('real_dollars', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Dólares reales')),
                ('real_dollar_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, verbose_name='Tasa dólar real')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.account', verbose_name='Cuenta')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.category', verbose_name='Categoría')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='organizations.organization', verbose_name='Organización')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.project', verbose_name='Proyecto')),
                ('valuation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.valuation', verbose_name='Valuación')),
            ],
            options={
                'verbose_name': 'Transacción',
                'verbose_name_plural': 'Transacciones',
            },
        ),
    ]
