# Generated by Django 6.0.5 on 2026-05-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_account_category_project_valuation_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(default='Cuenta Principal', max_length=255, verbose_name='Nombre de la cuenta'),
        ),
    ]
