# Generated by Django 6.0.5 on 2026-05-18 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='valuation',
            name='name',
            field=models.CharField(default='Valuación', max_length=255, verbose_name='Nombre de la valuación'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organizations.project', verbose_name='Proyecto'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valuation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organizations.valuation', verbose_name='Valuación'),
        ),
    ]
