# Generated by Django 6.0.5 on 2026-05-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_valuation_name_alter_transaction_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valuation',
            name='amount',
        ),
        migrations.AddField(
            model_name='valuation',
            name='amount_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto en Bolívares'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Monto en Dólares'),
        ),
        migrations.AddField(
            model_name='valuation',
            name='daily_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=20, verbose_name='Tasa del día'),
        ),
    ]
