# Generated by Django 5.2.5 on 2026-06-01 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_account_id_alter_category_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOrganizationAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_projects', to='organizations.organization', verbose_name='Organización')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_organizations', to='organizations.project', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Acceso de organización a proyecto',
                'verbose_name_plural': 'Accesos de organizaciones a proyectos',
                'unique_together': {('project', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='ProjectUserAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='organizations.project', verbose_name='Proyecto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Acceso de usuario a proyecto',
                'verbose_name_plural': 'Accesos de usuarios a proyectos',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
