# Generated by Django 5.2.5 on 2026-06-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_projectorganizationaccess_projectuseraccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('completado', 'Completado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='completado', max_length=20, verbose_name='Estado'),
        ),
    ]
