# Generated by Django 5.2.5 on 2026-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_account_bank_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_fee_bs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisión bancaria (Bs)'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_fee_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisión bancaria ($)'),
        ),
    ]
