# Generated by Django 5.2.5 on 2026-06-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_transaction_bank_fee_bs_transaction_bank_fee_usd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='real_dollar_rate',
        ),
    ]
