# Generated by Django 5.2.5 on 2026-06-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_remove_transaction_real_dollar_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_fee_real_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Comisión dólares reales ($)'),
        ),
    ]
