# Generated by Django 5.2.5 on 2026-06-22 15:56

from django.db import migrations, models

def migrate_category_to_categories(apps, schema_editor):
    Transaction = apps.get_model('organizations', 'Transaction')
    for t in Transaction.objects.all():
        if t.category_id:
            t.categories.add(t.category_id)

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_transaction_bank_fee_real_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='transactions', to='organizations.category', verbose_name='Categorías'),
        ),
        migrations.RunPython(migrate_category_to_categories, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
