# Generated by Django 5.2.5 on 2026-06-22 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_remove_transaction_category_transaction_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='Código')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='organizations.organization', verbose_name='Organización')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='organizations.costcenter', verbose_name='Centro de Costo'),
        ),
    ]
