# Generated by Django 5.2.5 on 2026-07-13 18:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_alter_account_id_alter_category_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_description', models.CharField(blank=True, max_length=255, verbose_name='Descripción (registro histórico)')),
                ('action', models.CharField(choices=[('created', 'Creada'), ('updated', 'Editada'), ('deleted', 'Eliminada')], max_length=10, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_audit_logs', to='organizations.organization', verbose_name='Organización')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.transaction', verbose_name='Transacción')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de auditoría de transacción',
                'verbose_name_plural': 'Registros de auditoría de transacciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
