# Generated by Django 5.2.5 on 2026-07-14 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_transactionauditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionauditlog',
            name='snapshot',
            field=models.JSONField(blank=True, null=True, verbose_name='Instantánea de la transacción'),
        ),
    ]
